#!/bin/sh

# time spark-submit --num-executors 15 --py-files data/zip/driver.zip --driver-library-path /user/lib/hadoop/lib/native:/usr/lib/hadoop/lib/hadoop-lzo.jar $PROJ/dig-mturk/spark/crfalign.py crfa istr58m 00 00 00 00001 "*" "" 600
# time spark-submit --num-executors 15 --py-files data/zip/driver.zip --driver-library-path /user/lib/hadoop/lib/native:/usr/lib/hadoop/lib/hadoop-lzo.jar $PROJ/dig-mturk/spark/crfalign.py crfa istr58m 00 00 00 00002 "*" "" 600
#time spark-submit --num-executors 15 --py-files data/zip/driver.zip --driver-library-path /user/lib/hadoop/lib/native:/usr/lib/hadoop/lib/hadoop-lzo.jar $PROJ/dig-mturk/spark/crfalign.py crfa istr58m 00 00 00 00003 "*" "" 600
#time spark-submit --num-executors 15 --py-files data/zip/driver.zip --driver-library-path /user/lib/hadoop/lib/native:/usr/lib/hadoop/lib/hadoop-lzo.jar $PROJ/dig-mturk/spark/crfalign.py crfa istr58m 00 00 00 00004 "*" "" 600
#time spark-submit --num-executors 15 --py-files data/zip/driver.zip --driver-library-path /user/lib/hadoop/lib/native:/usr/lib/hadoop/lib/hadoop-lzo.jar $PROJ/dig-mturk/spark/crfalign.py crfa istr58m 00 00 00 00005 "*" "" 600
# time spark-submit --num-executors 15 --py-files data/zip/driver.zip --driver-library-path /user/lib/hadoop/lib/native:/usr/lib/hadoop/lib/hadoop-lzo.jar $PROJ/dig-mturk/spark/crfalign.py crfa istr58m 00 00 00 00006 "*" "" 600
#time spark-submit --num-executors 15 --py-files data/zip/driver.zip --driver-library-path /user/lib/hadoop/lib/native:/usr/lib/hadoop/lib/hadoop-lzo.jar $PROJ/dig-mturk/spark/crfalign.py crfa istr58m 00 00 00 00007 "*" "" 600
# time spark-submit --num-executors 15 --py-files data/zip/driver.zip --driver-library-path /user/lib/hadoop/lib/native:/usr/lib/hadoop/lib/hadoop-lzo.jar $PROJ/dig-mturk/spark/crfalign.py crfa istr58m 00 00 00 00008 "*" "" 600
#time spark-submit --num-executors 15 --py-files data/zip/driver.zip --driver-library-path /user/lib/hadoop/lib/native:/usr/lib/hadoop/lib/hadoop-lzo.jar $PROJ/dig-mturk/spark/crfalign.py crfa istr58m 00 00 00 00009 "*" "" 600
# time spark-submit --num-executors 15 --py-files data/zip/driver.zip --driver-library-path /user/lib/hadoop/lib/native:/usr/lib/hadoop/lib/hadoop-lzo.jar $PROJ/dig-mturk/spark/crfalign.py crfa istr58m 00 00 00 00010 "*" "" 600
#time spark-submit --num-executors 15 --py-files data/zip/driver.zip --driver-library-path /user/lib/hadoop/lib/native:/usr/lib/hadoop/lib/hadoop-lzo.jar $PROJ/dig-mturk/spark/crfalign.py crfa istr58m 00 00 00 00011 "*" "" 600
# time spark-submit --num-executors 15 --py-files data/zip/driver.zip --driver-library-path /user/lib/hadoop/lib/native:/usr/lib/hadoop/lib/hadoop-lzo.jar $PROJ/dig-mturk/spark/crfalign.py crfa istr58m 00 00 00 00012 "*" "" 600
#time spark-submit --num-executors 15 --py-files data/zip/driver.zip --driver-library-path /user/lib/hadoop/lib/native:/usr/lib/hadoop/lib/hadoop-lzo.jar $PROJ/dig-mturk/spark/crfalign.py crfa istr58m 00 00 00 00013 "*" "" 600
# time spark-submit --num-executors 15 --py-files data/zip/driver.zip --driver-library-path /user/lib/hadoop/lib/native:/usr/lib/hadoop/lib/hadoop-lzo.jar $PROJ/dig-mturk/spark/crfalign.py crfa istr58m 00 00 00 00014 "*" "" 600
#time spark-submit --num-executors 15 --py-files data/zip/driver.zip --driver-library-path /user/lib/hadoop/lib/native:/usr/lib/hadoop/lib/hadoop-lzo.jar $PROJ/dig-mturk/spark/crfalign.py crfa istr58m 00 00 00 00015 "*" "" 600
# time spark-submit --num-executors 15 --py-files data/zip/driver.zip --driver-library-path /user/lib/hadoop/lib/native:/usr/lib/hadoop/lib/hadoop-lzo.jar $PROJ/dig-mturk/spark/crfalign.py crfa istr58m 00 00 00 00016 "*" "" 600
time spark-submit --num-executors 15 --py-files data/zip/driver.zip --driver-library-path /user/lib/hadoop/lib/native:/usr/lib/hadoop/lib/hadoop-lzo.jar $PROJ/dig-mturk/spark/crfalign.py crfa istr58m 00 00 00 00017 "*" "" 600
# time spark-submit --num-executors 15 --py-files data/zip/driver.zip --driver-library-path /user/lib/hadoop/lib/native:/usr/lib/hadoop/lib/hadoop-lzo.jar $PROJ/dig-mturk/spark/crfalign.py crfa istr58m 00 00 00 00018 "*" "" 600
#time spark-submit --num-executors 15 --py-files data/zip/driver.zip --driver-library-path /user/lib/hadoop/lib/native:/usr/lib/hadoop/lib/hadoop-lzo.jar $PROJ/dig-mturk/spark/crfalign.py crfa istr58m 00 00 00 00019 "*" "" 600
# time spark-submit --num-executors 15 --py-files data/zip/driver.zip --driver-library-path /user/lib/hadoop/lib/native:/usr/lib/hadoop/lib/hadoop-lzo.jar $PROJ/dig-mturk/spark/crfalign.py crfa istr58m 00 00 00 00020 "*" "" 600
